version: "3.6"


services:
  app:
    image: "mailround-ui"
    build:
      context: .
    ports:
      - 8000:80
    environment:
      MAILROUND_STATUS_LOG_PATH: /share/data.mrmp
    volumes:
      - ./data.mrmp:/share/data.mrmp